[versions]
kotlin = "2.0.21"

[libraries]
azure-speech-client-sdk = { module = "com.microsoft.cognitiveservices.speech:client-sdk", version = "1.41.1" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.9.0" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.0" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.12" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
